### PR TITLE
retrieve data in the streamlit app

### PR DESCRIPTION
**Pull request by millawell**

### CODE REVIEW

**Comment by jingzhaoou** [comment]
I am using the following solution. I hope to avoid using `numpy`. Of course, we don't have to save the data to a file if that is not required. A potential issue is that sending data from Javascript to Python seems quite slow. 

```js
      const blob = await fetch(data.url).then(r => r.blob());
      const blobData = await blob.arrayBuffer();
      const jsonBlobData = Buffer.from(blobData).toJSON()
      Streamlit.setComponentValue(jsonBlobData)
```

```python
    audiorec_data = st_audiorec()
    if audiorec_data is not None and 'data' in audiorec_data.keys():
      wav_data = audiorec_data['data']
      with open(f1, 'w+b') as fh:
        fh.write(bytes(wav_data))
```

**Comment by jingzhaoou** [comment]
This solution is much faster and works. Just that there are some weird errors on the Python side. 

```javascript
      const blob = await fetch(data.url).then(r => r.blob());
      const blobData = await blob.arrayBuffer();
      Streamlit.setComponentValue(blobData)
```

```python
    audiorec_data = st_audiorec()
    if audiorec_data is not None:
      wav_data = audiorec_data
      with open(f1, 'w+b') as fh:
        fh.write(wav_data)
```

**Comment by millawell** [comment]
I mean numpy is only used in that example which is totally not necessary, what one would do in the app is totally up to the user :)

**Comment by jingzhaoou** [comment]
@millawell Haha, totally agreed. I found that if we can pass the `arrayBuffer` directly to the Python side, the frontend handling seems be much faster.

**Review by stefanrmmr — APPROVED** [review]

**Pull request merged**
